### ISSUE TITLE
reload does not sort option arrays

### ISSUE THREAD

**Issue by skaldesh** [desertbit/grml#10]
Start with this grml.yaml file:  
```yaml
version: 1
project: test

options:
    runtime:
        - base
        - openvino
        - cuda
        - qt

```

Start grml and then change the grml.yaml to this:  
```yaml
version: 1
project: test

options:
    runtime:
        - new-runtime
        - base
        - openvino
        - cuda
        - qt

```

Do a `reload` inside grml --> The runtime is still at *base*
