### ISSUE TITLE
Crash with an unknown sub dependency

### ISSUE THREAD

**Issue by r0l1** [desertbit/grml#11]
```
    build:
        help: full build
        deps:
            - build.daemon
        commands:
            daemon:
                help: build the daemon application
                deps:
                    - generate
                    - build.report
```
