### ISSUE TITLE
Extend `deps:` to allow for multiple "pipelines", that run their commands in parallel

### ISSUE THREAD

**Issue by skaldesh** [desertbit/grml#12]
Imagine this current grml command:
```
...
build:
  help: build everything
  deps:
    - targetA
    - targetB.1
    - targetB.2
    - targetC
    - targetD
...
```

This is possible with the current stucture and would run the commands sequentially in the given order.  
But it would be desirable to run commands that do not depend on each other in parallel.

Let's say, that **targetA must be built before everything else**, and **targetB.1** must be built before **targetB.2**.  
The following execution would be optimal:
```
> start targetA
< wait until finished (abort if failed)
> start targetB.1
> start targetC
> start targetD
< wait until targetB.1 finished (abort if failed)
> start targetB.2
< wait until all finished (abort if failed)
```
